version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      labels:
          - "type: dependencies"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      labels:
          - "type: ci/cd"
